### ISSUE TITLE
Upgrade to Go 1.18

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/rsmt2d#105]
Upgrade to [Go 1.18](https://tip.golang.org/doc/go1.18) which is a prerequisite to https://github.com/celestiaorg/rsmt2d/issues/68

**Comment by rootulp** [comment]
> Note that Tendermint is still on 1.17

Thanks for flagging that! I just confirmed tendermint is indeed on Go 1.17 [here](https://github.com/tendermint/tendermint/blob/b71ec8c83fde289dc0504a01c2f3fd85216dc288/go.mod#L3). In https://github.com/tendermint/tendermint/pull/8924 they upgrade to mockery 2.14 which uses Go 1.18 [here](https://github.com/vektra/mockery/blob/v2.14.0/go.mod#L3=). Therefore, it seems possible for a 1.18 library to be used by a 1.17 application.

**Comment by adlerjohn** [comment]
We could always give it a try with a new release, and if it doesn't work then we revert. Better to find out now than later. :shipit:
