### ISSUE TITLE
Pass the axis and axis index when create a tree

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/rsmt2d#119]
In order to remove a leaky abstraction when creating cached merkle trees for extended data squares, we need to pass the axis and axis index to the tree [constructor](https://github.com/celestiaorg/rsmt2d/blob/e2ae439f5bafb8eb9368fd3c120caf1f45beef0f/tree.go#L10). This will also allow us to have parallelized nmt caches.

```go
Constructor(axis rsmt2d.Axis, index uint) rsmt2d.Tree
```

**Comment by musalbas** [comment]
#116 will resolve this once merged.
