### ISSUE TITLE
Expected behaviour of RowRoots() and ColRoots() on an incomplete EDS is undefined

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/rsmt2d#122]

**Comment by musalbas** [comment]
What is the current behavior now?

**Comment by musalbas** [comment]
Wondering if there's any reason where it would make sense to return row roots for an incomplete EDS, but I can't think of any.

**Comment by staheri14** [comment]
I think this might be relevant https://github.com/celestiaorg/rsmt2d/issues/214
