### ISSUE TITLE
`OR` instead `AND` should be used in the test check

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/rsmt2d#162]
The test `TestLazyRootGeneration`  will pass if only one of the root arrays is equal to the expected value, but not both of them. 

At the end of test [if statement](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/datasquare_test.go#L154-L156) should check if any of the root arrays has changed and then return an error. Thus `or` instead of `and` should be used.

**Comment by rootulp** [comment]
Thanks for flagging @andrijamitrovic23 ! The issue you described was actually masking a bug in the test:

https://github.com/celestiaorg/rsmt2d/blob/0153b50740c9156bcb4055b9a94d230b162cc9ac/datasquare_test.go#L142

should append to `colRoots`
