### ISSUE TITLE
Unnecessary index calculation

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/rsmt2d#164]
In the function `erasureExtendRow` when [setting a row slice](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatasquare.go#L164), the start index calculation `len(shares)-int(eds.originalDataWidth)` is unnecessary because `len(shares)` is the same as the `eds.originalDataWidth`.

Same problem exists in the [erasureExtendCol](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatasquare.go#LL167C1-L167C1) function as well.

**Comment by rootulp** [comment]
> because `len(shares)` is the same as the `eds.originalDataWidth`

Appears correct b/c https://github.com/rootulp/rsmt2d/blob/2e59fbaa585e44d26cc294edb89b51af48dc61eb/codecs.go#L15-L17
