### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/rsmt2d#171]
* [Col](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatasquare.go#L185-L193) function should use [deepCopy](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatasquare.go#LL211C1-L218C2) function same as it is done in [Row](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatasquare.go#LL202C1-L204C2) function to avoid duplication of code.

* [Flattened](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/datasquare.go#L306) should be used in [TestEdsRepairRoundtripSimple](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/rsmt2d_test.go#L44-L49) and [TestEdsRepairTwice](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/rsmt2d_test.go#L111-L115) tests to avoid duplication of code.

**Comment by rootulp** [comment]
While reviewing the draft rsmt2d audit report, I realized I only addresses the first bullet point in this issue.
