### ISSUE TITLE
Good coding practice

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/rsmt2d#177]
[Sanity checks](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L334-L392) within the `prerepairSanityCheck` function use four `if` statements but could use two. Because these checks are run in parallel using Go package `errgroup` the order of these does not matter. Thus grouping can be done that two `if` statements are used instead of four (l.e. Group two ([first](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L339-L351) and [second](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L367-L379)) statements under one `if rowIsComplete` and define `rowIsComplete` right before that if statement; do the same for `colIsComplete` if statements).

**Comment by andrijamitrovic23** [comment]
Its somewhat similar, I would only keep the same number of new go-routines:
```go
func (eds *ExtendedDataSquare) prerepairSanityCheck(
	rowRoots [][]byte,
	colRoots [][]byte,
) error {
	errs, _ := errgroup.WithContext(context.Background())

	for i := uint(0); i < eds.width; i++ {
		i := i
		
		rowIsComplete := noMissingData(eds.row(i), noShareInsertion)
		// if there's no missing data in this row
		if rowIsComplete {
			errs.Go(func() error {
				// ensure that the roots are equal
				rowRoot, err := eds.getRowRoot(i)
				if err != nil {
					return err
				}
				if !bytes.Equal(rowRoots[i], rowRoot) {
					return fmt.Errorf("bad root input: row %d expected %v got %v", i, rowRoots[i], rowRoot)
				}
			})

			errs.Go(func() error {
				parityShares, err := eds.codec.Encode(eds.rowSlice(i, 0, eds.originalDataWidth))
				if err != nil {
					return err
				}
				if !bytes.Equal(flattenChunks(parityShares), flattenChunks(eds.rowSlice(i, eds.originalDataWidth, eds.originalDataWidth))) {
					return &ErrByzantineData{Row, i, eds.row(i)}
				}
				return nil
			})
		}

		colIsComplete := noMissingData(eds.col(i), noShareInsertion)
		// if there's no missing data in this col
		if colIsComplete {
			errs.Go(func() error {
				// ensure that the roots are equal
				colRoot, err := eds.getColRoot(i)
				if err != nil {
					return err
				}
				if !bytes.Equal(colRoots[i], colRoot) {
					return fmt.Errorf("bad root input: col %d expected %v got %v", i, colRoots[i], colRoot)
				}
			})

			errs.Go(func() error {
				parityShares, err := eds.codec.Encode(eds.colSlice(0, i, eds.originalDataWidth))
				if err != nil {
					return err
				}
				if !bytes.Equal(flattenChunks(parityShares), flattenChunks(eds.colSlice(eds.originalDataWidth, i, eds.originalDataWidth))) {
					return &ErrByzantineData{Col, i, eds.col(i)}
				}
				return nil
			})
		}
	}

	return errs.Wait()
}
```
I see what you mean, I was only thinking on the side of fewer If statements and grouping logic regarding rows or columns. I'll leave for you to decide.

**Comment by rootulp** [comment]
Thanks for elaborating! Yea grouping seems fine to me and your code block looks just as readable as existing implementation so will address
