### ISSUE TITLE
ErrByzantineData.Shares are not filled

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/rsmt2d#178]
`ErrByzantineData.Shares` are not set when verification of newly completed orthogonal vectors returns a `ErrByzantineData` error ([first place](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L164-L167) and [second place](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L229-L232)). On the contrary, these shares are set if a verification of newly completed [row](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L152-L152) or [column](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L217) returns `ErrByzantineData` error.

When `ErrByznatineData` is raised it is propagated through `solveCrossword`, `Repair`, `Reconstruct`, `Retrieve`, where a new `ErrByzantine` is [created](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/eds/byzantine/byzantine.go#L32-L32). If the shares within are not filled, `GetProofsForShares`  will return an empty sequence of `sharesWithProof` and `ErrByzantine` is created with that empty sequence `sharesWithProof`. This is further propagated through [GetEDS](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/getters/ipld.go#L70-L70), [SharesAvailable](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/availability/full/availability.go#L57-L57), [sample](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/das/daser.go#L149-L149); until a [new](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/das/daser.go#L155-L155) BadEncodingProof[ is created](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/eds/byzantine/bad_encoding.go#L43-L43), and which will end up [propagated](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/das/daser.go#L155-L155) (the byzantine error is captured in [SharesAvailable](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/availability/full/availability.go#L73-L81)) to other nodes, with the field `Shares` being a sequence of `nil` values. Finally, when such a proof is received by other nodes, they [call](https://github.com/celestiaorg/go-fraud/blob/main/fraudserv/service.go#L186) `Validate` on it. Since the values in it are `nil`, [this loop](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/eds/byzantine/bad_encoding.go#L146-L157) is a no-op. Consequently, decoding of shares should fail, [resulting in an error](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/eds/byzantine/bad_encoding.go#LL162C1-L166C3).

We suggest filling in the shares with corresponding column or row data if the verification of that newly completed orthogonal column or row returns an `ErrByznatineData`.

**Comment by rootulp** [comment]
Thanks for identifying! 

I'm not sure I fully understand the `Shares` field of `ErrByzantineData`. It claims to be "Pre-repaired shares" but if the crossword is solved iteratively then I would expect it to be possible for the `Shares` inside `ErrByzantineData` to contain repaired shares from previous iterations of the `solveCrosswordRow` and `solveCrosswordCol` so does "Pre-repaired shares" in this context just refer to one iteration?

**Comment by Wondertan** [comment]
Might be related https://github.com/celestiaorg/rsmt2d/issues/112

**Comment by andrijamitrovic23** [comment]
> I'm not sure I fully understand the `Shares` field of `ErrByzantineData`. It claims to be "Pre-repaired shares" but if the crossword is solved iteratively then I would expect it to be possible for the `Shares` inside `ErrByzantineData` to contain repaired shares from previous iterations of the `solveCrosswordRow` and `solveCrosswordCol` so does "Pre-repaired shares" in this context just refer to one iteration?

I've realized that as well and understood that `Shares` could contain repaired cells from previous iteration.

**Comment by adlerjohn** [comment]
> does "Pre-repaired shares" in this context just refer to one iteration?

Yes, that's correct. In other words, it contains shares whose individual inclusion is guaranteed to be provable by the full node (i.e. shares usable in a BEFP).

**Comment by ivan-gavran** [comment]
In the description of the issue there is a small mistake, which is not affecting the fix. Nonetheless, let me bring it up: The `p.Shares` is not going to be an array of `nil`s, but rather an empty array. Thus, when a bad encoding proof is received by other nodes and they call the function `Validate` on it, an error will be raised upon checking the size of p.Shares, [here](https://github.com/celestiaorg/celestia-node/blob/0823f6b644eb6ba176ef5ae3c008c65018ed5f46/share/eds/byzantine/bad_encoding.go#L135-L135).

**Comment by ivan-gavran** [comment]
> Isn't the error returned by `verifyAgainstColRoots`, not `ErrByzantineData`, but an err returned by the Merkle tree implementation (which in the case of an NMT, would be e.g. an unordered share error)? The error is emitted [here](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L415).

In the scenario where the column root can be successfully computed, but it does not equal the expected root `colRoots[c]` it would return `ErrByzantineData`, [here](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword.go#L320-L322).

(Unless I am missing some reason for why those lines could not be reached.)
