### ISSUE TITLE
Unused attribute in test

### ISSUE THREAD

**Issue by andrijamitrovic23** [celestiaorg/rsmt2d#180]
There is an unused attribute [axis](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword_test.go#L180) in the test `TestCorruptedEdsReturnsErrByzantineData`. 

There are two options:

- remove it

- use as an expected value in the test to check the returned error of the function [Repair](https://github.com/celestiaorg/rsmt2d/blob/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword_test.go#LL202C2-L202C2)

**Comment by rootulp** [comment]
Based on https://github.com/celestiaorg/rsmt2d/blame/6515446be623987ded119e530900589f30e4c69e/extendeddatacrossword_test.go#L204 and failing test in [this commit](https://github.com/celestiaorg/rsmt2d/commit/fed004af5245644a526dfcdd8fd40e2c790d86e5) I'm assuming we can't test the Axis so it appears residual and will go with option 1: remove it.

cc: @distractedm1nd
