### ISSUE TITLE
Why rebuild extended shares?

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/rsmt2d#196]
## Context

https://github.com/celestiaorg/rsmt2d/blob/328fe4dba32ab858b06e60fde9f12252f7938450/extendeddatacrossword.go#L244-L275

## Question

Given that `Decode` returns the original shares + parity shares, why does `rebuildShares` have logic to separately rebuild extended shares? It seems possible to entirely remove the `isExtendedPartIncomplete` conditional.

**Comment by adlerjohn** [comment]
IIRC, Infectious behaves differently and `Decode` doesn't return all shares. Could you confirm?

**Comment by rootulp** [comment]
Ahh I see, thanks for pointing this out. It appears Infectious `Decode` did only return the rebuilt shares [here](https://github.com/celestiaorg/rsmt2d/pull/154/files#diff-b2ca25b4b25855e5d483204f9dfc73df2e2e2e3946cebafa0aed2e84dfb37e6aL74).

**Comment by adlerjohn** [comment]
This should probably have been originally fixed within the Infectious codec IMO, rather that doubling work for other codecs.
