### ISSUE TITLE
Consistent naming: shard, chunk, buffer, share

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/rsmt2d#215]
This repo uses the terms: `shard`, `chunk`, `buffer`, and `share` interchangeably. It may help readability if one word was chosen and usage was consistent across the repo.

**Comment by rootulp** [comment]
Update from #299 is to consolidate on share.

**Comment by musalbas** [comment]
This is just my opinion not a decision. Please get inputs from other engineers first such as @adlerjohn @renaynay @Wondertan.

**Comment by musalbas** [comment]
This is also relevant to the docs. Cc @jcstein @YazzyYaz

**Comment by adlerjohn** [comment]
Leaning towards agreeing with the conclusion in #299 to go with `share`.
