### ISSUE TITLE
Enforce required checks

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/rsmt2d#223]
## Problem

Currently there are no required checks on this repo so PRs can be merged that introduce regressions (i.e. fail unit tests or don't conform to linter).

## Proposal

Consider making these two required checks

<img width="855" alt="Screenshot 2023-07-05 at 1 08 11 PM" src="https://github.com/celestiaorg/rsmt2d/assets/3699047/34f4a364-b3c8-4fd8-b44b-7e8ee0185af3">

**Comment by adlerjohn** [comment]
Looks like this is done
