### ISSUE TITLE
bug: Allow to set chunkSize to be set in dataSquare

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/rsmt2d#231]
If DataSquare initialised without chunks, `SetCell` will return chunk size mismatch error on setting first chunk with non 0 size. We need a way to create square without chunks, that will allow `SetCell` and will be possible to use `GetCell` on. Currently, there is no way to initialise square, providing no chunks and setting `chunkSize` to non zero value at the same time.

Steps to reproduce: 
1. Create new DataSquare by `newDataSquare` with data list of 0 length.
2. Set shares by `SetCell`

Solution:
Add chunkSize param to the `newDataSquare` constructor

**Comment by Wondertan** [comment]
Additionally, we can follow implicit approach of the constructor and set chunk size on the first SetCell call

**Comment by Wondertan** [comment]
@walldiss could you provide an example of the code that is required to make it work correctly? Can be copied/directed from our hotfix
