### ISSUE TITLE
Inconsistent terminology in variable names: chunks vs shares

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/rsmt2d#262]
We use chunks and shares interchangeably in variable names and comments - we should stick to one, probably "chunks".

**Comment by rootulp** [comment]
Similar to https://github.com/celestiaorg/rsmt2d/issues/215. 

Out of curiosity why the preference for "chunks"? Since "shares" are commonly used in celestia-app, I have a slight preference for it.

**Comment by musalbas** [comment]
No particular reason other than it seems more intuitive or understandable
due to being less formal.
