### ISSUE TITLE
Benchmark computeRoots function for large square sizes

### ISSUE THREAD

**Issue by staheri14** [celestiaorg/rsmt2d#303]
In the context of the big blonk workstream, and based on the CPU profiling data, it has been hypothesized that the `computeRoots` function accounts for 30% of CPU usage. This was observed during an experiment conducted in testground, which involved block sizes ranging from 2 to 100 MB. To validate the duration this function takes, the `computeRoots` function must be benchmarked. If a benchmark already exists, it should be expanded to include larger data square sizes to accurately assess its performance.

**Comment by staheri14** [comment]
Including more context: below is the  flame graph associated with the cpu profiling data mentioned in the description of the issue:


![Screenshot 2024-03-04 at 5 22 12 PM](https://github.com/celestiaorg/rsmt2d/assets/35961250/bb40207b-3976-471d-a695-7f8fada544f4)

**Comment by Wondertan** [comment]
Most of the time seem to be spend on https://github.com/celestiaorg/nmt/issues/216
