### ISSUE TITLE
Names 2d coordinates of Row/Col are misleading. X, Y instead of Y, X

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/rsmt2d#314]
n the GetCell/SetCell functions, the input coordinates are reversed. For example, in the code [here](https://github.com/celestiaorg/rsmt2d/blob/2df5f8aa4709b7f3d2c5e647350b431f990ced75/datasquare.go#L311), the row is accessed using the X coordinate and the column with the Y coordinate. Traditionally, the X axis refers to the horizontal axis and the Y axis to the vertical. Therefore, the row index should be identified by Y, and the column index by X. This inconsistency also appears in other functions like col, getColRoot, colSlice, etc.

Example:
```
func (ds *dataSquare) rowSlice(x uint, y uint, length uint) [][]byte {
	return ds.squareRow[x][y : y+length]
}
```

Perhaps we should swap the use of X and Y coordinates in these functions and in other similar functions.

**Comment by rootulp** [comment]
Alternatively we can replace all usages of `x` and `y` with the more explicit `row` and `col`.

**Comment by walldiss** [comment]
The problem with `row` and `col` are usually used for variable pointing to axis slice itself. So it rather needs to be `rowIdx` and `colIdx`, which not so nice

**Comment by rootulp** [comment]
I'm fine with either: `rowIdx`/`colIdx` or fixing `x`/`y`
