### ISSUE TITLE
all: use SHA256 with SIMD instructions

### ISSUE THREAD

**Issue by odeke-em** [celestiaorg/rsmt2d#91]
As noticed in the paper, "Fraud and Data Availability Proofs", a recommendation was to use SHA256 with SIMD instructions. This task is to present such a library https://github.com/minio/sha256-simd as a replacement and tasked with demonstrating benchmark improvements in the PR to show how much faster this can improve.

Kindly cc-ing my colleague @elias-orijtech

**Comment by adlerjohn** [comment]
https://github.com/celestiaorg/nmt/pull/31

**Comment by rootulp** [comment]
Relevant: https://github.com/celestiaorg/rsmt2d/commit/c2c8078b5ef419c4303fc7c8cc09fa0ba31955df. This repo uses minio/sha256-simd [here](https://github.com/celestiaorg/rsmt2d/blob/91acbb1023e35787ffe5756767a0749c49ab626e/go.mod#L20) and doesn't use crypto/sha-256. If benchmarks are not necessary, can this issue be resolved?
