### ISSUE TITLE
api: `eds.Row` and `eds.Col` do not actually return copies

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/rsmt2d#99]
Since we work with nested slices, copy just copies the references to the inner slices. So a user modifying an `eds.Row` will actually modify the internal representation - this is not the intended behavior, correct? 

https://github.com/celestiaorg/rsmt2d/blob/e3daf260bc77f69ec3a4b7bbd4d1d7b13a6015fd/extendeddatasquare.go#L133-L152

**Comment by adlerjohn** [comment]
Thanks, good find!
